### ISSUE TITLE
Server crash after using an Activator

### ISSUE THREAD

**Issue by bloodyraoul** [shadowfacts/Activator#1]
I have crafted an Activator, put a coal ore in front, then put a mining drill inside then crash :

```
java.lang.NullPointerException: Ticking block entity
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:459)
    at de.ellpeck.actuallyadditions.mod.util.WorldUtil.playerHarvestBlock(WorldUtil.java:373)
    at de.ellpeck.actuallyadditions.mod.items.ItemDrill.tryHarvestBlock(ItemDrill.java:516)
    at de.ellpeck.actuallyadditions.mod.items.ItemDrill.breakBlocks(ItemDrill.java:463)
    at de.ellpeck.actuallyadditions.mod.items.ItemDrill.onBlockStartBreak(ItemDrill.java:268)
    at net.shadowfacts.activator.tileentity.TileEntityActivator.tryHarvestBlock(TileEntityActivator.java:436)
    at net.shadowfacts.activator.tileentity.TileEntityActivator.continueBreaking(TileEntityActivator.java:429)
    at net.shadowfacts.activator.tileentity.TileEntityActivator.func_145845_h(TileEntityActivator.java:245)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by shadowfacts** [comment]
This will prevent the crash, however the mining drill will not work.

There's not much I can do about this as it's either a bug with Forge or with Actually Additions, and neither are being maintained for 1.7.10 anymore.
